/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  items?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    priceAtPurchase?: number;
    _key: string;
  }>;
  total?: number;
  status?: "paid" | "shipped" | "delivered" | "cancelled";
  customer?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "customer";
  };
  clerkUserId?: string;
  email?: string;
  address?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  stripePaymentId?: string;
  createdAt?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  price?: number;
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  material?: "wood" | "metal" | "fabric" | "leather" | "glass";
  color?: "black" | "white" | "oak" | "walnut" | "grey" | "natural";
  dimensions?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  stock?: number;
  featured?: boolean;
  assemblyRequired?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  name?: string;
  clerkUserId?: string;
  stripeCustomerId?: string;
  createdAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Order | Product | SanityImageCrop | SanityImageHotspot | Category | Slug | Customer | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries/categories.ts
// Variable: ALL_CATEGORIES
// Query: *[  _type == "category"] | order(title asc) {  _id,  title,  "slug": slug.current,  "image": image{    asset->{      _id,      url    },    hotspot  }}
export type ALL_CATEGORIESResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;
// Variable: CATEGORY_BY_SLUG
// Query: *[  _type == "category"  && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  "image": image{    asset->{      _id,      url    },    hotspot  }}
export type CATEGORY_BY_SLUGResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
} | null;

// Source: ./sanity/queries/customers.ts
// Variable: CUSTOMER_BY_EMAIL_QUERY
// Query: *[  _type == "customer"  && email == $email][0]{  _id,  email,  name,  clerkUserId,  stripeCustomerId,  createdAt}
export type CUSTOMER_BY_EMAIL_QUERYResult = {
  _id: string;
  email: string | null;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: string | null;
  createdAt: string | null;
} | null;
// Variable: CUSTOMER_BY_STRIPE_ID_QUERY
// Query: *[  _type == "customer"  && stripeCustomerId == $stripeCustomerId][0]{  _id,  email,  name,  clerkUserId,  stripeCustomerId,  createdAt}
export type CUSTOMER_BY_STRIPE_ID_QUERYResult = {
  _id: string;
  email: string | null;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: string | null;
  createdAt: string | null;
} | null;

// Source: ./sanity/queries/orders.ts
// Variable: ORDERS_BY_USER
// Query: *[  _type == "order"  && clerkUserId == $clerkUserId] | order(createdAt desc) {  _id,  orderNumber,  total,  status,  createdAt,  "itemCount": count(items),  "itemNames": items[].product->name,  "itemImages": items[].product->images[0].asset->url}
export type ORDERS_BY_USERResult = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  itemNames: Array<string | null> | null;
  itemImages: Array<string | null> | null;
}>;
// Variable: ORDER_BY_ID
// Query: *[  _type == "order"  && _id == $id][0] {  _id,  orderNumber,  clerkUserId,  email,  items[]{    _key,    quantity,    priceAtPurchase,    product->{      _id,      name,      "slug": slug.current,      "image": images[0]{        asset->{          _id,          url        }      }    }  },  total,  status,  address{    name,    line1,    line2,    city,    postcode,    country  },  stripePaymentId,  createdAt}
export type ORDER_BY_IDResult = {
  _id: string;
  orderNumber: string | null;
  clerkUserId: string | null;
  email: string | null;
  items: Array<{
    _key: string;
    quantity: number | null;
    priceAtPurchase: number | null;
    product: {
      _id: string;
      name: string | null;
      slug: string | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  address: {
    name: string | null;
    line1: string | null;
    line2: string | null;
    city: string | null;
    postcode: string | null;
    country: string | null;
  } | null;
  stripePaymentId: string | null;
  createdAt: string | null;
} | null;
// Variable: RECENT_ORDERS
// Query: *[  _type == "order"] | order(createdAt desc) [0...$limit] {  _id,  orderNumber,  email,  total,  status,  createdAt}
export type RECENT_ORDERSResult = Array<{
  _id: string;
  orderNumber: string | null;
  email: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
}>;
// Variable: ORDER_BY_STRIPE_PAYMENT_ID
// Query: *[  _type == "order"  && stripePaymentId == $stripePaymentId][0]{ _id }
export type ORDER_BY_STRIPE_PAYMENT_IDResult = {
  _id: string;
} | null;

// Source: ./sanity/queries/products.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[  _type == "product"] | order(name asc) {  _id,  name,  "slug": slug.current,  description,  price,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  dimensions,  stock,  featured,  assemblyRequired}
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
}>;
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[  _type == "product"  && featured == true  && stock > 0] | order(name asc) [0...6] {  _id,  name,  "slug": slug.current,  description,  price,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  stock}
export type FEATURED_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[  _type == "product"  && category->slug.current == $categorySlug] | order(name asc) {  _id,  name,  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock}
export type PRODUCTS_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[  _type == "product"  && slug.current == $slug][0] {  _id,  name,  "slug": slug.current,  description,  price,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  dimensions,  stock,  featured,  assemblyRequired}
export type PRODUCT_BY_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
} | null;
// Variable: SEARCH_PRODUCTS_QUERY
// Query: *[  _type == "product"  && (    name match $searchQuery    || description match $searchQuery  )] | score(  boost(name match $searchQuery, 3),  boost(description match $searchQuery, 1)) | order(_score desc) {  _id,  _score,  name,  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock}
export type SEARCH_PRODUCTS_QUERYResult = Array<{
  _id: string;
  _score: null;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: FILTER_PRODUCTS_BY_NAME
// Query: *[  _type == "product"  && ($categorySlug == "" || category->slug.current == $categorySlug)  && ($color == "" || color == $color)  && ($material == "" || material == $material)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && (    $searchQuery == "" ||     lower(name) match "*" + lower($searchQuery) + "*" ||    lower(description) match "*" + lower($searchQuery) + "*" ||    lower(category->title) match "*" + lower($searchQuery) + "*"  )  && ($inStock == false || stock > 0)] | order(name asc) {  _id,  name,  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock}
export type FILTER_PRODUCTS_BY_NAMEResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: FILTER_PRODUCTS_BY_PRICE_ASC
// Query: *[  _type == "product"  && ($categorySlug == "" || category->slug.current == $categorySlug)  && ($color == "" || color == $color)  && ($material == "" || material == $material)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && (    $searchQuery == "" ||     lower(name) match "*" + lower($searchQuery) + "*" ||    lower(description) match "*" + lower($searchQuery) + "*" ||    lower(category->title) match "*" + lower($searchQuery) + "*"  )  && ($inStock == false || stock > 0)] | order(price asc) {  _id,  name,  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock}
export type FILTER_PRODUCTS_BY_PRICE_ASCResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: FILTER_PRODUCTS_BY_PRICE_DESC
// Query: *[  _type == "product"  && ($categorySlug == "" || category->slug.current == $categorySlug)  && ($color == "" || color == $color)  && ($material == "" || material == $material)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && (    $searchQuery == "" ||     lower(name) match "*" + lower($searchQuery) + "*" ||    lower(description) match "*" + lower($searchQuery) + "*" ||    lower(category->title) match "*" + lower($searchQuery) + "*"  )  && ($inStock == false || stock > 0)] | order(price desc) {  _id,  name,  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock}
export type FILTER_PRODUCTS_BY_PRICE_DESCResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: FILTER_PRODUCTS_BY_RELEVANCE
// Query: *[  _type == "product"  && ($categorySlug == "" || category->slug.current == $categorySlug)  && ($color == "" || color == $color)  && ($material == "" || material == $material)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && (    $searchQuery == "" ||     lower(name) match "*" + lower($searchQuery) + "*" ||    lower(description) match "*" + lower($searchQuery) + "*" ||    lower(category->title) match "*" + lower($searchQuery) + "*"  )  && ($inStock == false || stock > 0)] | score(  boost(lower(name) match "*" + lower($searchQuery) + "*", 3),  boost(lower(description) match "*" + lower($searchQuery) + "*", 1),  boost(lower(category->title) match "*" + lower($searchQuery) + "*", 2)) | order(_score desc, name asc) {  _id,  name,  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock}
export type FILTER_PRODUCTS_BY_RELEVANCEResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: PRODUCTS_BY_IDS
// Query: *[  _type == "product"  && _id in $ids] {  _id,  name,  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  stock}
export type PRODUCTS_BY_IDSResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  stock: number | null;
}>;
// Variable: OUT_OF_STOCK_PRODUCTS
// Query: *[  _type == "product"  && stock == 0] | order(name asc) {  _id,  name,  "slug": slug.current,  "image": images[0]{    asset->{      _id,      url    }  }}
export type OUT_OF_STOCK_PRODUCTSResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: AI_SEARCH_PRODUCTS
// Query: *[  _type == "product"  && (    $searchQuery == ""    || name match $searchQuery    || description match $searchQuery    || category->title match $searchQuery  )  && ($categorySlug == "" || category->slug.current == $categorySlug)  && ($material == "" || material == $material)  && ($color == "" || color == $color)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)] | order(name asc) [0...20] {  _id,  name,  "slug": slug.current,  description,  price,  "image": images[0]{    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  dimensions,  stock,  featured,  assemblyRequired}
export type AI_SEARCH_PRODUCTSResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[\n  _type == \"category\"\n] | order(title asc) {\n  _id,\n  title,\n  \"slug\": slug.current,\n  \"image\": image{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}": ALL_CATEGORIESResult;
    "*[\n  _type == \"category\"\n  && slug.current == $slug\n][0] {\n  _id,\n  title,\n  \"slug\": slug.current,\n  \"image\": image{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}": CATEGORY_BY_SLUGResult;
    "*[\n  _type == \"customer\"\n  && email == $email\n][0]{\n  _id,\n  email,\n  name,\n  clerkUserId,\n  stripeCustomerId,\n  createdAt\n}": CUSTOMER_BY_EMAIL_QUERYResult;
    "*[\n  _type == \"customer\"\n  && stripeCustomerId == $stripeCustomerId\n][0]{\n  _id,\n  email,\n  name,\n  clerkUserId,\n  stripeCustomerId,\n  createdAt\n}": CUSTOMER_BY_STRIPE_ID_QUERYResult;
    "*[\n  _type == \"order\"\n  && clerkUserId == $clerkUserId\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  total,\n  status,\n  createdAt,\n  \"itemCount\": count(items),\n  \"itemNames\": items[].product->name,\n  \"itemImages\": items[].product->images[0].asset->url\n}": ORDERS_BY_USERResult;
    "*[\n  _type == \"order\"\n  && _id == $id\n][0] {\n  _id,\n  orderNumber,\n  clerkUserId,\n  email,\n  items[]{\n    _key,\n    quantity,\n    priceAtPurchase,\n    product->{\n      _id,\n      name,\n      \"slug\": slug.current,\n      \"image\": images[0]{\n        asset->{\n          _id,\n          url\n        }\n      }\n    }\n  },\n  total,\n  status,\n  address{\n    name,\n    line1,\n    line2,\n    city,\n    postcode,\n    country\n  },\n  stripePaymentId,\n  createdAt\n}": ORDER_BY_IDResult;
    "*[\n  _type == \"order\"\n] | order(createdAt desc) [0...$limit] {\n  _id,\n  orderNumber,\n  email,\n  total,\n  status,\n  createdAt\n}": RECENT_ORDERSResult;
    "*[\n  _type == \"order\"\n  && stripePaymentId == $stripePaymentId\n][0]{ _id }": ORDER_BY_STRIPE_PAYMENT_IDResult;
    "*[\n  _type == \"product\"\n] | order(name asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  description,\n  price,\n  \"images\": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  material,\n  color,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}": ALL_PRODUCTS_QUERYResult;
    "*[\n  _type == \"product\"\n  && featured == true\n  && stock > 0\n] | order(name asc) [0...6] {\n  _id,\n  name,\n  \"slug\": slug.current,\n  description,\n  price,\n  \"images\": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  stock\n}": FEATURED_PRODUCTS_QUERYResult;
    "*[\n  _type == \"product\"\n  && category->slug.current == $categorySlug\n] | order(name asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"image\": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  material,\n  color,\n  stock\n}": PRODUCTS_BY_CATEGORY_QUERYResult;
    "*[\n  _type == \"product\"\n  && slug.current == $slug\n][0] {\n  _id,\n  name,\n  \"slug\": slug.current,\n  description,\n  price,\n  \"images\": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  material,\n  color,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}": PRODUCT_BY_SLUG_QUERYResult;
    "*[\n  _type == \"product\"\n  && (\n    name match $searchQuery\n    || description match $searchQuery\n  )\n] | score(\n  boost(name match $searchQuery, 3),\n  boost(description match $searchQuery, 1)\n) | order(_score desc) {\n  _id,\n  _score,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"image\": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  material,\n  color,\n  stock\n}": SEARCH_PRODUCTS_QUERYResult;
    "*[\n  _type == \"product\"\n  && ($categorySlug == \"\" || category->slug.current == $categorySlug)\n  && ($color == \"\" || color == $color)\n  && ($material == \"\" || material == $material)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && (\n    $searchQuery == \"\" || \n    lower(name) match \"*\" + lower($searchQuery) + \"*\" ||\n    lower(description) match \"*\" + lower($searchQuery) + \"*\" ||\n    lower(category->title) match \"*\" + lower($searchQuery) + \"*\"\n  )\n  && ($inStock == false || stock > 0)\n] | order(name asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"images\": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  material,\n  color,\n  stock\n}": FILTER_PRODUCTS_BY_NAMEResult;
    "*[\n  _type == \"product\"\n  && ($categorySlug == \"\" || category->slug.current == $categorySlug)\n  && ($color == \"\" || color == $color)\n  && ($material == \"\" || material == $material)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && (\n    $searchQuery == \"\" || \n    lower(name) match \"*\" + lower($searchQuery) + \"*\" ||\n    lower(description) match \"*\" + lower($searchQuery) + \"*\" ||\n    lower(category->title) match \"*\" + lower($searchQuery) + \"*\"\n  )\n  && ($inStock == false || stock > 0)\n] | order(price asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"images\": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  material,\n  color,\n  stock\n}": FILTER_PRODUCTS_BY_PRICE_ASCResult;
    "*[\n  _type == \"product\"\n  && ($categorySlug == \"\" || category->slug.current == $categorySlug)\n  && ($color == \"\" || color == $color)\n  && ($material == \"\" || material == $material)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && (\n    $searchQuery == \"\" || \n    lower(name) match \"*\" + lower($searchQuery) + \"*\" ||\n    lower(description) match \"*\" + lower($searchQuery) + \"*\" ||\n    lower(category->title) match \"*\" + lower($searchQuery) + \"*\"\n  )\n  && ($inStock == false || stock > 0)\n] | order(price desc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"images\": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  material,\n  color,\n  stock\n}": FILTER_PRODUCTS_BY_PRICE_DESCResult;
    "*[\n  _type == \"product\"\n  && ($categorySlug == \"\" || category->slug.current == $categorySlug)\n  && ($color == \"\" || color == $color)\n  && ($material == \"\" || material == $material)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && (\n    $searchQuery == \"\" || \n    lower(name) match \"*\" + lower($searchQuery) + \"*\" ||\n    lower(description) match \"*\" + lower($searchQuery) + \"*\" ||\n    lower(category->title) match \"*\" + lower($searchQuery) + \"*\"\n  )\n  && ($inStock == false || stock > 0)\n] | score(\n  boost(lower(name) match \"*\" + lower($searchQuery) + \"*\", 3),\n  boost(lower(description) match \"*\" + lower($searchQuery) + \"*\", 1),\n  boost(lower(category->title) match \"*\" + lower($searchQuery) + \"*\", 2)\n) | order(_score desc, name asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"images\": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  material,\n  color,\n  stock\n}": FILTER_PRODUCTS_BY_RELEVANCEResult;
    "*[\n  _type == \"product\"\n  && _id in $ids\n] {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"image\": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  stock\n}": PRODUCTS_BY_IDSResult;
    "*[\n  _type == \"product\"\n  && stock == 0\n] | order(name asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  \"image\": images[0]{\n    asset->{\n      _id,\n      url\n    }\n  }\n}": OUT_OF_STOCK_PRODUCTSResult;
    "*[\n  _type == \"product\"\n  && (\n    $searchQuery == \"\"\n    || name match $searchQuery\n    || description match $searchQuery\n    || category->title match $searchQuery\n  )\n  && ($categorySlug == \"\" || category->slug.current == $categorySlug)\n  && ($material == \"\" || material == $material)\n  && ($color == \"\" || color == $color)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n] | order(name asc) [0...20] {\n  _id,\n  name,\n  \"slug\": slug.current,\n  description,\n  price,\n  \"image\": images[0]{\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  material,\n  color,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}": AI_SEARCH_PRODUCTSResult;
  }
}
